### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by RtKelleher** [Hestat/ClamAV-CortexAnalyzer#1]
Followed your guide and installed on Ubuntu 18.04 receiving the following error when running the analyzer. Appears to be a permission issue with the standard APT install, I changed the user to root as you suggested on your blog.
 
{
  "summary": {
    "taxonomies": [
      {
        "level": "malicious",
        "namespace": "Clamscan",
        "predicate": "Match",
        "value": "1 rule(s)"
      }
    ]
  },
  "full": {
    "results": [
      "{'/tmp/cortex-job-AWl35zMk_-6AQJ66zVpT-7266962267196958439': ('ERROR', 'Access denied.')}"
    ]
  },
  "success": true,
  "artifacts": [],
  "operations": []
}

● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Wed 2019-03-13 12:43:41 EDT; 7min ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
  Process: 31068 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
  Process: 31067 ExecStartPre=/bin/mkdir /run/clamav (code=exited, status=1/FAILURE)
 Main PID: 31069 (clamd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service
           └─31069 /usr/sbin/clamd --foreground=true

**Comment by daskydasky** [comment]
Did you manage to resolve this? I'm having the same issue. Looks like Clam has no access to the file created by Cortex.

WARNING: lstat() failed on: /tmp/cortex-job-AXCqJfZC1uQC3ddfBLUE-3674585604146022107/input/attachment4932164484590739478

**Comment by Passimist** [comment]
I am having the same issue. I added the clamav user to the cortex group but the error still occurrs.
Did you fix it?

**Comment by daskydasky** [comment]
Not yet, still an issue.

**Comment by Passimist** [comment]
I ll post it here in case I fix it. Wish me luck ;)

**Comment by Passimist** [comment]
So I have some good news and some bad ones...
The good:
I fixed the problem for me.
Run `dmesg | less -S`
Here (if you have the same cause of the problem) you can see that apparmor is blocking something.
According to this https://bugs.launchpad.net/ubuntu/+source/clamav/+bug/1842695 the Apparmor profiles for clamav are outdated.
now run:
`apt-get update`
`apt-get install apparmor-utils`
`aa-complain /usr/sbin/clamd`
`then restart clamav-daemon.service`

The bad:
While is makes it work for me the workaround obviously disables some security features. So use with caution!
To undo the aa-complain run: `aa-enforce /usr/sbin/clamd`
**EDIT: Better than disabeling apparmor you can run `aa-logprof` to update the profile so that the actions that were blocked are allowed.**



Let me know if this helped.
